ARG CUDA_VERSION="11.8.0"
ARG CUDNN_VERSION="8"
ARG UBUNTU_VERSION="22.04"

# # Base NVidia CUDA Ubuntu image
FROM nvidia/cuda:$CUDA_VERSION-cudnn$CUDNN_VERSION-devel-ubuntu$UBUNTU_VERSION AS base

RUN apt-get clean && apt-get update && \
    apt-get install locales curl git nano libhdf5-dev unzip ffmpeg python3-pyaudio rsync wget libasound-dev portaudio19-dev libportaudio2 libportaudiocpp0 -y && \
    locale-gen en_US.UTF-8

RUN curl pyenv.run | bash

SHELL ["/bin/bash", "--login", "-c"]

ARG CONDA_VERSION="miniconda3-3.10-23.11.0-2"

ENV HOME=/root

RUN echo 'echo "profile"' >> ~/.profile
RUN echo 'export HOME=/root' >> ~/.profile
RUN echo 'export PYENV_ROOT="$HOME/.pyenv"' >> ~/.profile
RUN echo "export PATH='${PYENV_ROOT}/bin:$PATH'" >> ~/.profile
RUN echo 'eval "$(pyenv init -)"' >> ~/.profile

RUN pyenv install ${CONDA_VERSION}
RUN pyenv global ${CONDA_VERSION}
RUN conda init bash

ENV PATH "/root/.pyenv/versions/miniconda3-3.10-23.11.0-2/bin/:$PATH"

ARG BRANCH="main"
ARG USER="AHarmlessPyro"
ARG REPO="GeneFacePlusPlus"

ADD https://api.github.com/repos/${USER}/${REPO}/git/refs/heads/$BRANCH version.json
RUN git clone --depth 1 -b $BRANCH https://github.com/$USER/$REPO.git

RUN pwd
RUN ls -la /GeneFacePlusPlus

WORKDIR /GeneFacePlusPlus

RUN conda create -n geneface -y
SHELL ["conda", "run", "-n", "geneface", "/bin/bash", "-c"]

RUN conda env update --file env.yaml -n geneface
RUN pip install -r requirements.txt --no-build-isolation

# RUN mim install mmcv==2.1.0

# RUN wget http://es.archive.ubuntu.com/ubuntu/pool/main/libf/libffi/libffi7_3.3-4_amd64.deb
# RUN dpkg -i libffi7_3.3-4_amd64.deb

# # Hack to rebuild on branch update


# RUN pip install -r docs/prepare_env/requirements.txt -v
# RUN bash docs/prepare_env/install_ext.sh

# RUN pip install -r server_requirements.txt

# RUN gdown --folder https://drive.google.com/drive/folders/1o4t5YIw7w4cMUN4bgU9nPf6IyWVG1bEk -O ./deep_3drecon/
# RUN gdown --folder https://drive.google.com/drive/folders/1FqvNbQgOSkvVO8i-vCDJmKM4ppPZjUpL -O ./checkpoints/